repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # this is optional, use `pre-commit autoupdate` to get the latest rev!
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

  - repo: local
    hooks:
#      - id: yapf
#        name: yapf
#        entry: yapf -ir -vv ./src
#        language: system
#        always_run: true
#        pass_filenames: false
      - id: flake8
        name: flake8
        entry: flake8 /src --indent-size=4 --select=F,E112,E113,E203,E304,E502,E702,E703,E71,E72,E731,W191,W6 --statistics -j4 --exit-zero
        language: system
        always_run: true
        pass_filenames: false
      - id: tests
        name: tests
        entry: pytest tests
        language: system
        always_run: false
        pass_filenames: false
